/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        /* ── Light mode base tokens ── */
        "primary":                  "var(--color-primary)",
        "on-primary":               "var(--color-on-primary)",
        "primary-container":        "var(--color-primary-container)",
        "on-primary-container":     "var(--color-on-primary-container)",
        "secondary":                "var(--color-secondary)",
        "on-secondary":             "var(--color-on-secondary)",
        "secondary-container":      "var(--color-secondary-container)",
        "on-secondary-container":   "var(--color-on-secondary-container)",
        "surface":                  "var(--color-surface)",
        "on-surface":               "var(--color-on-surface)",
        "on-surface-variant":       "var(--color-on-surface-variant)",
        "surface-variant":          "var(--color-surface-variant)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "surface-container-low":    "var(--color-surface-container-low)",
        "surface-container":        "var(--color-surface-container)",
        "surface-container-high":   "var(--color-surface-container-high)",
        "surface-container-highest":"var(--color-surface-container-highest)",
        "surface-dim":              "var(--color-surface-dim)",
        "surface-bright":           "var(--color-surface-bright)",
        "surface-tint":             "var(--color-surface-tint)",
        "background":               "var(--color-background)",
        "on-background":            "var(--color-on-background)",
        "outline":                  "var(--color-outline)",
        "outline-variant":          "var(--color-outline-variant)",
        "error":                    "var(--color-error)",
        "on-error":                 "var(--color-on-error)",
        "error-container":          "var(--color-error-container)",
        "on-error-container":       "var(--color-on-error-container)",
        "inverse-surface":          "var(--color-inverse-surface)",
        "inverse-on-surface":       "var(--color-inverse-on-surface)",
        "inverse-primary":          "var(--color-inverse-primary)",
        "tertiary":                 "var(--color-tertiary)",
        "on-tertiary":              "var(--color-on-tertiary)",
        "primary-fixed":            "var(--color-primary-fixed)",
        "primary-fixed-dim":        "var(--color-primary-fixed-dim)",
        "on-primary-fixed":         "var(--color-on-primary-fixed)",
        "secondary-fixed":          "var(--color-secondary-fixed)",
        "secondary-fixed-dim":      "var(--color-secondary-fixed-dim)",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        full: "9999px",
        pebble: "16px",
        input: "8px",
        btn: "8px",
      },
      spacing: {
        sm: "2px",
        "max-width": "1100px",
        unit: "4px",
        md: "8px",
        lg: "12px",
        xl: "16px",
        xs: "1px",
        "container-padding": "16px",
        section: "32px",
        pebble: "12px",
      },
      fontFamily: {
        sans: ["Inter", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "sans-serif"],
      },
      fontSize: {
        "body-md": ["13px", { lineHeight: "1.4", letterSpacing: "0", fontWeight: "400" }],
        "label-sm": ["9px", { lineHeight: "1.1", letterSpacing: "0.01em", fontWeight: "500" }],
        display: ["24px", { lineHeight: "1.1", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-md": ["16px", { lineHeight: "1.2", letterSpacing: "0", fontWeight: "600" }],
        "headline-lg": ["20px", { lineHeight: "1.1", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-bold": ["11px", { lineHeight: "1.2", letterSpacing: "0.01em", fontWeight: "600" }],
        "body-lg": ["14px", { lineHeight: "1.4", letterSpacing: "0", fontWeight: "400" }],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
  ],
};
